<?php

/**
 * @file
 * Functions to support theming in the starbase theme.
 */

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function starbase_theme_suggestions_page_alter(array &$suggestions, array $variables, $hook) {
  $page = $variables['page'];
  // suggest a page--sidebar.html.twig template if current page is rendering the sidebar region
  if (isset($page['page_sidebar'])) {
    $suggestions[] = $hook . '__' . 'sidebar';
  }
}
